$(document).ready(function(){
    $("button.question").click(function(){
        if($(this).next().hasClass("on")){
            $("div.on").hide();
            $(this).next().removeClass("on");
        }
        else{
            $(this).next().addClass("on");
            $("div.on").show();
        }
    })
})